name: Daily Stock Scan
on:
  schedule:
    - cron: '30 10 * * 1-5' # Indian Time: 4:00 PM
  workflow_dispatch: # Manual run ke liye

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Version v2 se v4 kar diya (Warning khatam)
        
      - name: Set up Python
        uses: actions/setup-python@v5 # Version v2 se v5 kar diya (Warning khatam)
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
