name: Hourly Stock Scan
on:
  schedule:
    # Indian Time ke hisaab se har ghante ka schedule (9:30, 10:30, 11:30, 12:30, 1:30, 2:30, 3:30, 4:30)
    - cron: '00 04 * * 1-5'
    - cron: '00 05 * * 1-5'
    - cron: '00 06 * * 1-5'
    - cron: '00 07 * * 1-5'
    - cron: '00 08 * * 1-5'
    - cron: '00 09 * * 1-5'
    - cron: '00 10 * * 1-5'
    - cron: '00 11 * * 1-5'
  workflow_dispatch: # Manual button ke liye

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
